# Generated by Django 5.2.17 on 2026-08-24 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_notification_user_pricealert_user_product_tracked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_type', models.CharField(max_length=50)),
                ('mae', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rmse', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('r2_score', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('trained_samples', models.PositiveIntegerField(default=0)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AI Model Metric',
                'verbose_name_plural': 'AI Model Metrics',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='AIPricePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField(auto_now=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('predicted_price_7_days', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('predicted_price_14_days', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('predicted_price_30_days', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trend', models.CharField(default='STABLE', max_length=20)),
                ('recommendation', models.CharField(default='WAIT', max_length=20)),
                ('recommendation_strength', models.CharField(default='Wait', max_length=30)),
                ('recommendation_reason', models.TextField(blank=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_reason', models.TextField(blank=True)),
                ('historical_average', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('historical_minimum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('historical_maximum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('model_name', models.CharField(default='RandomForestRegressor', max_length=100)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_predictions', to='dashboard.product')),
            ],
            options={
                'verbose_name': 'AI Price Prediction',
                'verbose_name_plural': 'AI Price Predictions',
                'ordering': ['-updated_at'],
            },
        ),
    ]
